// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from image_cache.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

class ImageCache {
public:
    virtual ~ImageCache() {}

    static std::shared_ptr<ImageCache> create_with_path(const std::string & path);

    virtual std::string cache_path() = 0;

    virtual std::vector<uint8_t> image_for_key(const std::string & key) = 0;

    virtual void save_image_for_key(const std::string & key, const std::vector<uint8_t> & image_data) = 0;
};
