// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from image_cache.djinni

#import "ImageCache.h"
#import <Foundation/Foundation.h>


@protocol ImageCache

+ (id <ImageCache>)createWithPath:(NSString *)path;

- (NSString *)cachePath;

- (NSData *)imageForKey:(NSString *)key;

- (void)saveImageForKey:(NSString *)key imageData:(NSData *)imageData;

@end
