// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from image_cache.djinni

#import "ImageCache.h"
#import "ImageCacheCppProxy.h"
#include "image_cache.hpp"
#import "DJICppWrapperCache+Private.h"
#import <Foundation/Foundation.h>
#include <memory>

@interface ImageCacheCppProxy ()

@property (nonatomic, readonly) std::shared_ptr<ImageCache> cppRef;

+ (id)imageCacheWithCpp:(const std::shared_ptr<ImageCache> &)cppRef;

- (id)initWithCpp:(const std::shared_ptr<ImageCache> &)cppRef;

@end
