// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from image_cache.djinni

#import "ImageCache.h"
#import <Foundation/Foundation.h>

@interface ImageCacheCppProxy : NSObject <ImageCache>
@end
